# Generated by Django 4.0 on 2022-10-24 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del director.', max_length=255)),
                ('apellidos', models.CharField(help_text='Ingrese los apellidos del director.', max_length=255)),
                ('imagen', models.CharField(help_text='Ingrese la url de una imagen del director.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ingrese el título.', max_length=255)),
                ('año', models.IntegerField(help_text='Ingrese el año de lanzamiento.')),
                ('imagen', models.CharField(help_text='Ingrese la url de la potada.', max_length=255)),
                ('descripcion', models.CharField(help_text='Ingrese una breve despcripción.', max_length=100)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.directores')),
            ],
        ),
    ]
