# Generated by Django 4.0 on 2022-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='director',
        ),
        migrations.AddField(
            model_name='directores',
            name='peliculas',
            field=models.ManyToManyField(to='biblioteca.Peliculas'),
        ),
    ]
