# Generated by Django 4.0 on 2022-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_peliculas_director_directores_peliculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Directores',
        ),
        migrations.DeleteModel(
            name='Peliculas',
        ),
    ]
