# Generated by Django 4.0 on 2022-10-24 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_bibliotea_delete_directores_delete_peliculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del director.', max_length=255)),
                ('apellidos', models.CharField(help_text='Ingrese los apellidos del director.', max_length=255)),
                ('imagen', models.CharField(help_text='Ingrese la url de una imagen del director.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ingrese el título.', max_length=255)),
                ('año', models.IntegerField(help_text='Ingrese el año de lanzamiento.')),
                ('imagen', models.CharField(help_text='Ingrese la url de la potada.', max_length=255)),
                ('descripcion', models.CharField(help_text='Ingrese una breve despcripción.', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bibliotea',
        ),
        migrations.AddField(
            model_name='directores',
            name='peliculas',
            field=models.ManyToManyField(to='biblioteca.Peliculas'),
        ),
    ]
