# Generated by Django 4.0 on 2022-10-24 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_directores_peliculas_delete_bibliotea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del director.', max_length=100)),
                ('apellidos', models.CharField(help_text='Ingrese los apellidos del director.', max_length=100)),
                ('imagen', models.CharField(help_text='Ingrese la url de una imagen del director.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ingrese el título.', max_length=255)),
                ('año', models.IntegerField(help_text='Ingrese el año de lanzamiento.')),
                ('imagen', models.CharField(help_text='Ingrese la url de la potada.', max_length=255)),
                ('descripcion', models.CharField(help_text='Ingrese una breve despcripción.', max_length=100)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.director')),
                ('genero', models.ManyToManyField(to='biblioteca.Genero')),
            ],
        ),
        migrations.DeleteModel(
            name='Directores',
        ),
        migrations.DeleteModel(
            name='Peliculas',
        ),
    ]
